version: '3'

services:
  next-app:
    container_name: next-jenkins-demo
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname